GET http://localhost:5000/subscribers

###

GET http://localhost:5000/subscribers/63abcd7bf55f05922ea75fcb

###

POST http://localhost:5000/subscribers
Content-Type: application/json

{
    "name": "Amazing Person",
    "subscribedToChannel": "Web Dev Simplified"
}

###

DELETE http://localhost:5000/subscribers/63abd045b2918c1aa82cb5c4

###

PATCH http://localhost:5000/subscribers/63abd045b2918c1aa82cb5c4
Content-Type: application/json

{
    "name": "New Name",
}
